#' Match VRI Records to MSYT Yield Curves
#'
#' Joins the VRI for the AOI to existing managed stand yield table (MSYT) curves
#' based on matching feature id. MSYT curves are provided by the govn't of BC under a
#' data sharing agreement and are protected. Matching records have pre-calculated
#' yield projections generated by TIPSY to age 120. The join should return
#' only managed stands (e.g. Managed: Planted/Natural), but could include aggregate
#' curves, the latter of which should be inspected.
#'
#'
#' @param vri_data sf object. VRI polygon data, typically created by create_vri_subset()
#' @param msyt_curves_path Character. Path to MSYT_prov_current_input_output.csv file
#' @param msyt_reference_path Character. Path to MSYT_prov_reference.csv file
#' @param output_file Character. Optional path to save results as CSV. If NULL, no file is saved
#'
#' @return A list containing:
#' \describe{
#'   \item{vri_with_msyt}{sf object with VRI polygons that have MSYT curves}
#'   \item{msyt_summary}{data.frame summarizing MSYT curve availability}
#' }
#'
#' @details This function performs several key operations:
#' 1. Reads MSYT yield curve data and reference tables
#' 2. Joins VRI data to MSYT output curves by FEATURE_ID
#' 3. Adds reference information (area, current_yield type, BEC zone)
#' 4. Creates visualizations of volume projections by polygon
#' 5. Identifies which stands have managed yield curves vs. need VDYP processing
#'
#' The MSYT tables contain pre-calculated yield curves for managed stands up to age 120.
#' Records with current_yield = "VDYP" require processing through VDYP7console.
#'
#' @examples
#' \dontrun{
#' # Load VRI subset
#' vri_subset <- create_vri_subset(gdb_path, bbox_coords = c(-124, 59, -123.5, 59.5))
#'
#' # Match to MSYT curves
#' msyt_results <- match_vri_to_msyt_curves(
#'   vri_data = vri_subset,
#'   msyt_curves_path = "MSYT_prov_current_input_output.csv",
#'   msyt_reference_path = "MSYT_prov_reference.csv",
#'   output_file = "vri_msyt_matched.csv"
#' )
#'
#' # View results
#' print(msyt_results$msyt_summary)
#' }
#'
#' @export
#' @import sf
#' @import dplyr
#' @import ggplot2
#' @importFrom data.table fwrite
#' @importFrom dplyr inner_join select group_by summarise mutate
#' @importFrom sf st_drop_geometry
#' @importFrom tidyr pivot_longer
match_vri_to_msyt_curves <- function(vri_data,
                                     msyt_curves_path,
                                     msyt_reference_path,
                                     output_file = NULL) {

  # Validate inputs
  if (!inherits(vri_data, "sf")) {
    stop("vri_data must be an sf object")
  }

  if (!file.exists(msyt_curves_path)) {
    stop("MSYT curves file not found: ", msyt_curves_path)
  }

  if (!file.exists(msyt_reference_path)) {
    stop("MSYT reference file not found: ", msyt_reference_path)
  }

  if (!"FEATURE_ID" %in% names(vri_data)) {
    stop("vri_data must contain a FEATURE_ID column")
  }

  # Read MSYT files
  message("Reading MSYT yield curves...")
  msyt_curves <- readr::read_csv(msyt_curves_path, show_col_types = FALSE)

  message("Reading MSYT reference data...")
  msyt_reference <- readr::read_csv(msyt_reference_path, show_col_types = FALSE)

  # Validate MSYT data structure
  if (!"feature_id" %in% names(msyt_curves)) {
    stop("MSYT curves file must contain a 'feature_id' column")
  }

  if (!"feature_id" %in% names(msyt_reference)) {
    stop("MSYT reference file must contain a 'feature_id' column")
  }

  # Check for VDYP records that shouldn't have MSYT curves
  msyt_vdyp_records <- msyt_reference %>%
    filter(current_yield == "VDYP")

  vdyp_with_curves <- inner_join(msyt_vdyp_records, msyt_curves, by = "feature_id")

  if (nrow(vdyp_with_curves) > 0) {
    warning("Found ", nrow(vdyp_with_curves), " records with current_yield='VDYP' that have MSYT curves. These should not have curves.")
  }

  # Select only the necessary columns from the MSYT data to prevent duplicates
  msyt_curves_select <- msyt_curves %>%
    dplyr::select(feature_id, starts_with("MVcon"), starts_with("MVdec"))

  msyt_reference_select <- msyt_reference %>%
    dplyr::select(feature_id, area, current_yield, bec_zone)

  # Join VRI to MSYT curves
  message("Joining VRI data to MSYT curves...")
  vri_with_msyt <- vri_data %>%
    inner_join(msyt_curves_select, by = c("FEATURE_ID" = "feature_id"))

  message("Found ", nrow(vri_with_msyt), " VRI records with MSYT curves")

  # Add reference information
  vri_with_msyt <- vri_with_msyt %>%
    inner_join(msyt_reference_select, by = c("FEATURE_ID" = "feature_id")) %>%
    select(FEATURE_ID,
           SPECIES_CD_1, SPECIES_CD_2, SPECIES_CD_3,
           area, current_yield, bec_zone, everything())

  # Create summary
  msyt_summary <- vri_with_msyt %>%
    sf::st_drop_geometry() %>%
    group_by(current_yield, bec_zone) %>%
    summarise(
      count = n(),
      total_area = sum(area, na.rm = TRUE),
      mean_mvcon_80 = mean(MVcon_80, na.rm = TRUE),
      mean_mvdec_80 = mean(MVdec_80, na.rm = TRUE),
      .groups = "drop"
    )

  # Save output if requested
  if (!is.null(output_file)) {
    message("Saving results to: ", output_file)
    # Properly remove geometry and handle list columns
    output_data <- vri_with_msyt %>%
      sf::st_drop_geometry() %>%
      as.data.frame()

    # Check for and handle list columns that fwrite can't handle
    list_cols <- sapply(output_data, is.list)
    if (any(list_cols)) {
      warning("Converting ", sum(list_cols), " list columns to character for CSV export")
      for (col in names(output_data)[list_cols]) {
        output_data[[col]] <- as.character(output_data[[col]])
      }
    }

    # Use write.csv as fallback if fwrite still fails
    tryCatch({
      data.table::fwrite(output_data, output_file, na = "")
    }, error = function(e) {
      warning("fwrite failed, using write.csv instead: ", e$message)
      write.csv(output_data, output_file, row.names = FALSE, na = "")
    })
  }

  # Return results
  result <- list(
    vri_with_msyt = vri_with_msyt,
    msyt_summary = msyt_summary
  )

  message("Matching complete. ", nrow(vri_with_msyt), " records matched to MSYT curves.")

  return(result)
}
